name: Deploy to GitHub Pages

on:
  push:
    branches:
      - Production
  pull_request:
    types: [closed]
    branches:
      - Production

jobs:
  build-and-deploy:
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: 📥 Install dependencies
        run: yarn install

      - name: 🛠 Set deploy environment variable
        run: echo "DEPLOY_TARGET=gh-pages" >> $GITHUB_ENV

      - name: 🔧 Build and prepare for deployment
        run: yarn predeploy # Use the predeploy script which builds the project

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
